[package]
name = "rust-native-core-ios"
version = "0.1.0"
edition = "2024"

[dependencies]
core-foundation = "0.10.0"
objc2 = "0.6.1"
objc2-foundation = "0.3.1"

rust-native-core = { path = "../rust-native-core" }

ahash = { workspace = true }
