[package]
name = "example-android"
version = "0.1.0"

[apk]
package_name = "com.rustnative.example"
target_sdk_version = 33
min_sdk_version = 21
icon = "res/icon.png"
assets = "assets"
resources = "res"
build_targets = ["aarch64-linux-android"]
java_sources = ["./android/src/main/java"]

[dependencies]
android_logger = "*"
