[package]
name = "example-android"
version = "0.1.0"
edition = "2024"

[dependencies]
rust-native-core-android = { path = "../rust-native-core-android" }

[package.metadata.android]
package = "com.rustnative"
build_targets = ["aarch64-linux-android"]

[lib]
name = "main"
crate-type = ["cdylib"]
